### ISSUE TITLE
Symbols won't be exported on ABCL

### ISSUE THREAD

**Issue by fukamachi** [tpapp/cl-colors#6]
Although this may be a bug of ABCL, some symbols (ex. `RGB-RED`) won't be exported though they are specified in `:export` of `defpackage`.

```
CL-USER(1): (ql:quickload :cl-colors)
To load "cl-colors":
  Load 1 ASDF system:
    cl-colors
; Loading "cl-colors"
[package cl-colors]
......
(:CL-COLORS)
CL-USER(2): (apropos "rgb-red")
CL-COLORS::RGB-RED (fbound)                 ;; <- not exported
```

It worked well if I removed the part unexporting symbols.

```diff
diff --git a/package.lisp b/package.lisp
index b559140..af16901 100644
--- a/package.lisp
+++ b/package.lisp
@@ -2,6 +2,7 @@
 
 (in-package #:common-lisp-user)
 
+#-abcl
 (eval-when (:compile-toplevel :load-toplevel :execute)
   ;; this is needed because the color names in the autogenerated file are
   ;; exported manually and some implementations (eg SBCL) complain about the
```

**Comment by fukamachi** [comment]
I also reported it on ABCL's mailing-list.
http://thread.gmane.org/gmane.lisp.armedbear.devel/3328

**Comment by tpapp** [comment]
Thanks for reporting this. I don't use ABCL, but if you have a fix I am happy to accept a pull request.

**Comment by tpapp** [comment]
I decided to rewrite parsing and generate an export list — I think that this is the kosher solution. Commit bc9b0415daf32006b8318b12c59958db75d9b6e7 is in the development branch, please test it and let me know if it works on ABCL, then I can merge it.

**Comment by fukamachi** [comment]
It looks no problem on ABCL. Thanks.

**Comment by tpapp** [comment]
Thanks for testing, merged to master.
