### ISSUE TITLE
No longer exporting color constants?

### ISSUE THREAD

**Issue by quicklisp** [tpapp/cl-colors#8]
The older version of cl-colors exported things like `cl-colors:+black+` via `define-rgb-color`. It does not seem like the new version does that any more. This breaks a number of projects which reference `cl-colors:+black+` and other stuff. Is this package change intentional or accidental?

**Comment by tpapp** [comment]
Thanks for reporting, it was a typo. Fixed by 9340ccdffe from @Ferada.
